export { default as Alert } from './component/alert'
export { Tag, CheckableTag } from './component/tag'
export { default as Badge } from './component/badge'
export { default as Switch } from './component/switch'
export { default as Tooltip } from './component/tooltip'
